package com.example.hospital.model;


import jakarta.persistence.*;

/**
 * *******************************************************
 * Package: com.example.hospital.model
 * File: Patient.java
 * Author: Ochwada
 * Date: Monday, 30.Jun.2025, 4:57 PM
 * Description: Represents a Patient Entity in a Hospital's system.
 * Objective:
 * *******************************************************
 */

@Entity
@Table(name = "patient")
public class Patient {

    /**
     * The unique identifier for the staff.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Full name of the patient
     */
    private String name;

    /**
     * Medical diagnosis provided for the patient
     */
    private String diagnosis;

    /**
     * Total bill amount for the patient's treatment
     */
    private double billAmount;

    /**
     * The doctor assigned to this patient.
     * This establishes a many-to-one relationship (many patients → one doctor).
     */
    @ManyToOne
    @JoinColumn(name = "assigned_doctor_id")
    private Staff assignedDoctor;

    /**
     * Default no-argument constructor.
     * <p>
     * Required by JPA and other frameworks for entity initialization.
     */
    public Patient() {
    }

    /**
     * Constructs a Patient with the specified name, diagnosis, bill amount, and assigned doctor.
     *
     * @param name           the full name of the patient
     * @param diagnosis      the medical diagnosis for the patient
     * @param billAmount     the total cost of treatment
     * @param assignedDoctor the doctor assigned to this patient
     */
    public Patient(String name, String diagnosis, double billAmount, Staff assignedDoctor) {
        this.name = name;
        this.diagnosis = diagnosis;
        this.billAmount = billAmount;
        this.assignedDoctor = assignedDoctor;
    }

    //----------------- Getters and Setters -----------------
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDiagnosis() {
        return diagnosis;
    }

    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }

    public double getBillAmount() {
        return billAmount;
    }

    public void setBillAmount(double billAmount) {
        this.billAmount = billAmount;
    }

    public Staff getAssignedDoctor() {
        return assignedDoctor;
    }

    public void setAssignedDoctor(Staff assignedDoctor) {
        this.assignedDoctor = assignedDoctor;
    }
}
