package com.example.hospital.model;


import jakarta.persistence.*;

/**
 * *******************************************************
 * Package: com.example.hospital.model
 * File: Staff.java
 * Author: Ochwada
 * Date: Monday, 30.Jun.2025, 4:37 PM
 * Description:  Represents a Stuff  Entity in a Hospital  management system.
 * Objective:
 * *******************************************************
 */

@Entity
@Table(name = "staff")
public class Staff {

    /**
     * The unique identifier for the staff.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Full name of the staff member
     */
    @Column
    private String name;

    /**
     * Role assigned to the staff member (e.g., DOCTOR, NURSE, ADMIN)
     */
    @Column
    private Role role;

    /**
     * Department the staff member belongs to (e.g., Cardiology, Pediatrics)
     */
    @Column
    private String department;

    /**
     * Default constructor required for frameworks like Spring or JPA
     */
    public Staff() {
    }

    /**
     * Constructs a staff member with a specified role, name, and department.
     *
     * @param role       the role of the staff member
     * @param name       the full name of the staff member
     * @param department the department the staff member is assigned to
     */
    public Staff(Role role, String name, String department) {
        this.role = role;
        this.name = name;
        this.department = department;
    }

    // -------------- Getters and Setters --------------

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }
}
